# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Mapbox Samples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Mapbox Samples
  pod 'Mapbox-iOS-SDK'

  target 'Mapbox SamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mapbox SamplesUITests' do
    # Pods for testing
  end

end
