# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chips_Material_IO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chips_Material_IO
  pod 'MaterialComponents/Chips'

end
