# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextField_Material_io' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextField_Material_io
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  
end
